import { DISCLAIMER_SHORT } from "@/lib/disclaimer";
import { resolveInventionTitle } from "@/lib/ideas/title";
import {
  DEVELOPMENT_TIMELINE_FIELDS,
  buildIdeaSummaryFields,
  buildTimelineReadiness,
  getTimelineFieldValue,
} from "@/lib/packet";
import { computeOverallReadinessScore } from "@/lib/readiness";
import type { ProjectRecord } from "@/lib/types";

function section(heading: string, lines: string[]): string {
  return [`## ${heading}`, "", ...lines, ""].join("\n");
}

/**
 * A plain-text record of what the inventor entered, readable without the app.
 * Deliberately the inventor's own words plus their readiness score — it makes no
 * assessment the packet does not already make.
 */
export function buildIntakeSummaryMarkdown(
  record: ProjectRecord,
  savedReferenceCount = 0,
): string {
  const title = resolveInventionTitle(record.answers, record.title);
  const created = new Date(record.createdAt);
  const createdLabel = Number.isNaN(created.getTime())
    ? "Unknown"
    : created.toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });

  const parts: string[] = [
    `# ${title}`,
    "",
    `Intake summary generated by SmartProBonoIP.`,
    "",
    section("Overview", [
      `- Started: ${createdLabel}`,
      `- Packet preparation score: ${computeOverallReadinessScore(record, savedReferenceCount)} / 100`,
      `- Saved prior-art references: ${savedReferenceCount}`,
    ]),
  ];

  const summaryLines = buildIdeaSummaryFields(record.answers)
    .filter((field) => field.value.trim().length > 0)
    .flatMap((field) => [`**${field.label}**`, "", field.value, ""]);

  if (summaryLines.length > 0) {
    parts.push(section("Your idea", summaryLines));
  }

  const timeline = record.developmentTimeline ?? {};
  const timelineLines = DEVELOPMENT_TIMELINE_FIELDS.map((field) => {
    const value = getTimelineFieldValue(timeline, field);
    return value ? `- ${field}: ${value}` : null;
  }).filter((line): line is string => line !== null);

  if (timelineLines.length > 0) {
    parts.push(
      section("Development timeline", [
        ...timelineLines,
        "",
        `Timeline readiness: ${buildTimelineReadiness(timeline)}`,
      ]),
    );
  }

  parts.push(section("Important", [DISCLAIMER_SHORT]));

  return parts.join("\n");
}

export function intakeSummaryFileName(recordId: string): string {
  return `smartprobonoip-intake-summary-${recordId.slice(0, 8)}.md`;
}
